debug: false
bot:
  # Name of your bot
  name: "placeholder"

  # Current version of your bot
  version: "0.1"

# Application - API Settings
api:
  # Twitch Application Client Id
  twitch_client_id: YOURTOKENHERE

  # Twitch Application Client Secret
  twitch_client_secret: YOURSECRETHERE

# Credentials
credentials:
  # OAuth Token for IRC USer (You can get yours here: http://twitchapps.com/tmi/)
  irc: YOUROAUTHHERE

# Channels - The bot will connect to all listed channels
channels:
  - YOURTWITCHCHANNELHERE

discordBroadcast: true